# Generated by Django 4.2 on 2023-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="img",
            field=models.FileField(
                default="https://res.cloudinary.com/dnxhcbb0u/image/upload/v1683561882/defaults/avatar/Oreo_bglowz.svg",
                upload_to="users",
            ),
        ),
    ]
