# Generated by Django 4.2 on 2023-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="img",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.FileField(
                default="https://res.cloudinary.com/dnxhcbb0u/image/upload/v1683561882/defaults/avatar/Kiki_guacg9.svg",
                upload_to="users",
            ),
        ),
    ]
