# Generated by Django 4.2 on 2023-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_img_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(
                default="https://res.cloudinary.com/dnxhcbb0u/image/upload/v1683561882/defaults/avatar/George_uhyhyt.svg",
                upload_to="users",
            ),
        ),
    ]
