# Generated by Django 4.2 on 2023-05-08 18:57

from django.db import migrations, models
import users.assets.avatar


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(
                default=users.assets.avatar.get_random_avatar, upload_to="users"
            ),
        ),
    ]
