# Generated by Django 4.2.1 on 2023-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.FileField(
                default="https://res.cloudinary.com/dnxhcbb0u/image/upload/v1683571920/defaults/author/author_rpspwb.jpg",
                max_length=1000,
                upload_to="authors",
            ),
        ),
    ]
