# Generated by Django 4.2.1 on 2023-05-08 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookloan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="authors.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="following",
            field=models.ManyToManyField(
                related_name="followed_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
