# Generated by Django 4.2 on 2023-05-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
