# Generated by Django 4.2.1 on 2023-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="days",
            field=models.IntegerField(
                choices=[("7", "Week"), ("15", "Fortnight"), ("30", "Month")],
                default="7",
            ),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="load_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="return_date",
            field=models.DateField(),
        ),
    ]
