# Generated by Django 4.2.1 on 2023-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookloan",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
