# Generated by Django 4.2.1 on 2023-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_days_alter_bookloan_load_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="is_avaliable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="days",
            field=models.IntegerField(
                choices=[(7, "Week"), (15, "Fortnight"), (30, "Month")], default=7
            ),
        ),
    ]
